Repository VeryGoodOpenSource/very_good_coverage, pull requests merged in 2020-10, with the labels that each got.

#11 ci: update workflow
  .github/workflows/test.yml
  README.md
Labels: enhancement

#13 feat: added support to exclude files
  .github/workflows/test.yml
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  index.js
  index.test.js
  package-lock.json
  package.json
Labels: enhancement

#14 chore: generate code after npm run all
  dist/index.js
  dist/index.js.map
Labels: bug

#23 chore: CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#22 docs: feature and bug issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#21 docs: pull_request_template
  .github/pull_request_template.md
Labels: documentation

#24 docs: add logo and update README format
  README.md
  assets/logo.png
Labels: documentation, enhancement

#25 docs: update logo asset
  README.md
  assets/logo.png
Labels: documentation, enhancement
